xridge/kubestone

Dockerfile, Makefile, config/default/manager_image_patch.yaml, config/manager/manager.yaml
=> FIX: make deploy does not instantiate the operator

.gitignore, main.go
* use the same restClientConfig for Clientset and Client
* use XXXOrDie() functions to simplify code
* organize imports
=> FIX: use one restClientConfig

config/crd/kustomization.yaml
This fixes the issue outlined in #28
=> FIX: Kustomize 3.1.0 compatibility

api/v1alpha1/iperf3_types.go, config/crd/bases/perf.kubestone.xridge.io_iperf3s.yaml, controllers/iperf3/clientpod.go, controllers/iperf3/controller.go, controllers/iperf3/serverdeployment.go, controllers/iperf3/serverdeployment_test.go, controllers/iperf3/serverservice.go, controllers/iperf3/suite_test.go, go.mod, go.sum, pkg/k8s/client.go, pkg/k8s/eventrecorder.go
=> ENH: iperf3 complete workflow

README.md
=> ENH: Extend developer documentation

api/v1alpha1/iperf3_types.go
=> ENH: Add kubebuilder.printcolumn to iperf3 status

config/rbac/role.yaml, controllers/fio/controller.go
=> FIX Added missing create configmap privilege

controllers/fio/controller.go, controllers/fio/job.go, pkg/k8s/client.go
=> MAINT: Moved isJobFinished() to k8s.client

docs/source/index.rst, docs/source/install.md, docs/source/quickstart.md
=> ENH: Use hyperlinks in documentation

.github/release-drafter.yml
Config for this app: https://github.com/toolmantim/release-drafter
=> ENH: Add config for release drafter github app

config/samples/fio/overlays/custom_jobs/patch.yaml, tests/e2e/fio_test.go, tests/e2e/iperf3_test.go, tests/e2e/suite_test.go, tests/e2e/sysbench_test.go
=> ENH Added end to end test for fio

config/rbac/role.yaml, controllers/iperf3/clientjob.go, controllers/iperf3/clientjob_test.go, controllers/iperf3/controller.go, controllers/iperf3/serverdeployment.go, controllers/iperf3/serverservice.go, pkg/k8s/client.go, tests/e2e/iperf3_test.go
=> FIX: Iperf3 connectivity in GKE

.github/config.yml
=> Only create TODOs for 'TODO:'

controllers/common/job.go, controllers/iperf3/serverdeployment.go, controllers/iperf3/serverservice.go
=> MAINT: make resource labels consistent with FQDN

docs/benchmarks/pgbench.md, docs/benchmarks/status.md, mkdocs.yml
=> DOC: Add documentation for pgbench

api/v1alpha1/qperf_types.go, config/crd/bases/perf.kubestone.xridge.io_qperves.yaml, config/crd/kustomization.yaml, config/crd/patches/cainjection_in_qperves.yaml, config/crd/patches/webhook_in_qperves.yaml, docs/static/apidocs.html
Created to address the issue shown in #140
=> FIX: Include qperf CRD in kustomize build

docs/benchmarks/status.md
Per @otto-von-bivouac 's ask in #142
=> DOC: Add reference to memory benchmark (via sysbench)

controllers/drill/job.go, controllers/drill/job_test.go, tests/e2e/drill_test.go
=> Fixed the drill pod

docs/quickstart.md, pkg/k8s/client.go, pkg/k8s/client_test.go, pkg/k8s/eventrecorder.go
=> ENH: More idiomatic event reasons

config/rbac/role.yaml, controllers/drill/controller.go, controllers/fio/controller.go, controllers/ioping/controller.go, controllers/iperf3/controller.go, controllers/pgbench/controller.go, controllers/qperf/controller.go, controllers/sysbench/controller.go, docs/static/apidocs.html
OpenShift requires update privileges on finalizers endpoint.
=> FIX: Add finalizers RBAC role to run on OpenShift

renovate.json
=> Revert "MAINT: Configure Renovate"

config/default/kustomization.yaml, config/default/namespace.yaml
=> add creation of namespace to kustomize

Makefile, config/default/kustomization.yaml, docs/quickstart.md, docs/static/apidocs.html
=> update to fix bug #176 in quickstart instructions

controllers/esrally/controller.go, controllers/esrally/job.go
=> Cleanup esrally
